# Generated by Django 4.0.6 on 2022-10-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='district',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='mandal',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='village',
            field=models.CharField(max_length=50),
        ),
    ]
