# Generated by Django 4.0.6 on 2022-10-06 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('profiles', '0002_alter_location_country_alter_location_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='qr_login',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('key', models.CharField(max_length=40)),
            ],
        ),
    ]
