# Generated by Django 4.0.6 on 2022-10-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_qr_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_login',
            name='key',
            field=models.CharField(max_length=64),
        ),
    ]
