# Generated by Django 4.0.6 on 2022-10-17 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_qr_login_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr_login',
            name='key',
        ),
    ]
