# Generated by Django 4.0.6 on 2022-11-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.ImageField(default='none', upload_to='products/'),
        ),
    ]
