# Generated by Django 4.0.6 on 2022-11-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0003_products_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(default='products/dummy.jpg', upload_to='products/'),
        ),
    ]
